services:
  db:
    image: postgres:16
    container_name: eduasiste_db
    restart: always
    volumes:
      - eduasiste_pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5431:5432"

volumes:
  eduasiste_pgdata:
